packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  bcrypt: true
  dtrace-provider: set this to true or false
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@expo/eas-build-job@21.0.2'
  - '@expo/eas-json@21.0.2'
  - '@expo/steps@21.0.2'
  - eas-cli@21.0.2
overrides:
  metro-cache: 0.81.5
  react: 19.1.0
  react-dom: 19.1.0
